module.exports = {
  CELL_PADDING: 5,
  CELL_SIZE: 30,
  CHAR_POINT: '$',
  CHAR_SNAKE_HEAD: 'X',
  CHAR_SNAKE_TAIL: 'x',
  FN_TIMEOUT_SECONDS: 10,
  LOCAL_STORAGE_REDUX_KEY: 'snake-heuristics:redux',
  SNAKE_LENGTH: 4,
  MAX_USER_SOLUTIONS: 5,
  CLOUD_CANVAS_SIZE: 15,
  CLOUD_RUN_TIMES: 3,
};
